modLoader           = "javafml"
loaderVersion = "[40.0,)"
license = "https://github.com/splatcraft/splatcraft-forge/blob/HEAD/LICENSE"

[[mods]]
modId           = "splatcraft"
displayName     = "Splatcraft"
description = '''
        Splatcraft is a Minecraft mod based on Nintendo's popular game Splatoon!
        This mod aims to add items and mechanics based on the game in a cohesive way, such as Turf Wars, Weapons, Squid Transformations and many more!
    '''

authors = "Cibernet, Octol1ttle"
credits = '''
        Thanks to Nintendo and Mojang, for making such great games!

        Programming and Design by Cibernet and Octol1ttle
        Models by Cibernet & JustHatless
        French translation by Flyse and Este
        Portuguese translation by gatoazulado
        Simplified Chinese translation by White Mind
        Spanish translation by Cibernet and Chichi
        Russian translation by jskces
        Italian translation by Alessio798

        Block of Power Eggs texture by rose bushes

        Special Thanks to Andante and seamuskills
        '''

logoFile = "pack.png"

version = "${file.jarVersion}"
updateJSONURL = "https://api.modrinth.com/updates/splatcraft/forge_updates.json"

displayURL = "https://curseforge.com/minecraft/mc-mods/splatcraft"
issueTrackerURL = "https://github.com/splatcraft/splatcraft-forge/issues"

[[dependencies.splatcraft]]
modId           = "forge"
mandatory = true
versionRange = "[40.2.0,)"
ordering = "NONE"
side            = "BOTH"
[[dependencies.splatcraft]]
modId           = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side            = "BOTH"
